# Simple Reinforcement Learning with Tensorflow: Part 0 - Q-Tables
In this iPython notebook we implement a Q-Table algorithm that solves the FrozenLake problem. To learn more, read here: https://medium.com/@awjuliani/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0

For more reinforcment learning tutorials, see:
https://github.com/awjuliani/DeepRL-Agents

In [6]:
import gym
import numpy as np
import random
import matplotlib.pyplot as plt
%matplotlib inline

### Load the environment

In [7]:
env = gym.make('FrozenLake-v0')

[2017-09-26 11:23:28,640] Making new env: FrozenLake-v0


### Implement Q-Table learning algorithm

In [8]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [9]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.525


In [10]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  1.93082899e-01   8.39046651e-03   7.15631436e-03   3.70222809e-03]
 [  4.50776000e-04   3.37677394e-03   1.73912029e-04   1.63804755e-01]
 [  1.23349018e-03   1.89396157e-03   3.90356423e-04   1.52573944e-01]
 [  2.77962455e-06   2.46428661e-04   7.12016767e-04   9.68246649e-02]
 [  3.06173101e-01   1.43192604e-03   8.26500020e-04   1.62396013e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.48134865e-01   1.21832815e-04   5.61450371e-05   8.73816327e-06]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  8.18591397e-04   3.53232470e-05   2.34606838e-04   3.57433873e-01]
 [  2.97867448e-03   2.18016605e-01   1.65354808e-03   0.00000000e+00]
 [  1.87262075e-01   1.10205570e-03   1.08037300e-04   9.34610903e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.03567432e-04   9.71314430e-04   5.03517009e-01   1